[package]
name = "caty_blog"
version = "0.1.0"
authors = ["Anthony Martinez", "Caty Christy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
glob = "0.3.0"
tera = "1.7.0"
pulldown-cmark = { version = "0.8", default-features = false, features = ["simd"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'
