[site]
name = "My Awesome Blog!"
author = "Neo"
topics = ["one", "two", "three"]

[creds]
user = "admin"
password = "123456"
token = "my very secret token"

[docpaths]
templates = "/var/www/site/templates"
webroot = "/var/www/site/webroot"
