[blog]
name = "My Awesome Blog!"
author = "Neo"
topics = ["one", "two", "three"]

[creds]
user = "admin"
password = "123456"

[logging]
level = "INFO"

[docpaths]
templates = "/var/www/blog/templates"
webroot = "/var/www/blog/webroot"
