[site]
name = "My Awesome Blog!"
author = "Neo"
url = "https://something.cool.here"
template = "special.tmpl"
topics = ["one", "two", "three", "gallery"]

[server]
bind = "0.0.0.0"
port = 8901

[docpaths]
templates = "test_files/site/templates"
webroot = "test_files/site/webroot"

[mime_types]
css = "text/css"
gif = "image/gif"
jpg = "image/jpeg"
